config:
    authorization:
        claims-token.validity-in-millisecond: 12000
        refresh-token.validity-in-millisecond: 3600
        anonymous-token.validity-in-millisecond: 3600
    idp:
        endpoint: http://sit3-ecs.rhbcloud.com/dcp-identity-service/login
        
