config:
    authorization:
        claims-token.validity-in-millisecond: 12000
        refresh-token.validity-in-millisecond: 3600
        anonymous-token.validity-in-millisecond: 3600
    idp:
        endpoint: http://sit2-ecs.mycloud.com/identity-service/login
        
